name: Build and Deploy
  uses: actions/checkout@v3
  with:
    app_location: "/"  # Change if your HTML files are inside a subfolder (e.g., "public")
    output_location: ""  # No build step needed for HTML/CSS sites
       
